import Head from "next/head";
import React, { useState } from "react";

import { Amplify, API } from "aws-amplify";
import awsconfig from "../src/aws-exports";

import CreateTodo from "../components/CreateTodo";
import Todo from "../components/Todos";

import * as mutations from "../src/graphql/mutations";
import * as queries from "../src/graphql/queries";

Amplify.configure(awsconfig);

export default function Home({ todos }) {
  const [todoList, setTodoList] = useState(todos);

  const onCreateTodo = async (todo) => {
    const newTodo = {
      title: todo,
      completed: false,
    };

    try {
      await API.graphql({
        query: mutations.createTodo,
        variables: { input: newTodo },
      });

      setTodoList((list) => [...list, { ...newTodo }]);

      console.log("Successfully created a todo!");
    } catch (err) {
      console.log("error: ", err);
    }
  };

  const onDeleteTodo = async (id) => {
    try {
      await API.graphql({
        query: mutations.deleteTodo,
        variables: { input: { id } },
      });

      const filterTodo = todoList.filter((todo) => todo.id !== id);
      setTodoList(filterTodo);

      console.log("Successfully deleted a todo!");
    } catch (err) {
      console.log({ err });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CreateTodo onCreateTodo={onCreateTodo} />
        <Todo todoList={todoList} onDeleteTodo={onDeleteTodo} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const todoData = await API.graphql({
    query: queries.listTodos,
  });

  return {
    props: {
      todos: todoData.data.listTodos.items,
    }
  };
}
